// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzaigiyjymphcsxiqymu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6YWlnaXlqeW1waGNzeGlxeW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDc4NTYsImV4cCI6MjA2MDI4Mzg1Nn0.HlepYAB7RNbBvB1-VCQ3NzY6oNDUV9W9hM16rB4UcAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);